/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import cjb.ci.Validaciones;
import java.awt.Component;
import java.awt.Container;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class PanelDetalle extends javax.swing.JPanel
{

    public JLabel getLblNombreProducto()
    {
        return lblNombreProducto;
    }

    public void setLblNombreProducto(JLabel lblNombreProducto)
    {
        this.lblNombreProducto = lblNombreProducto;
    }

    /**
     * Creates new form detalle
     */
    public PanelDetalle(String nombre, String precioUnitario)
    {

        initComponents();
        jtfPrecioU.setText(precioUnitario);
        lblNombreProducto.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblNombreProducto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCantidad = new javax.swing.JTextField();
        jtfPrecioU = new javax.swing.JTextField();
        jtfSubtotal = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 236, 238));
        setMaximumSize(new java.awt.Dimension(800, 110));
        setMinimumSize(new java.awt.Dimension(800, 110));
        setPreferredSize(new java.awt.Dimension(500, 110));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreProducto.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblNombreProducto.setText("NombreProducto");
        add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 461, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Precio Unitario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Subtotal");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 61, -1));

        jtfCantidad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCantidad.setText("1");
        jtfCantidad.setToolTipText("");
        jtfCantidad.setPreferredSize(new java.awt.Dimension(70, 25));
        jtfCantidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfCantidadActionPerformed(evt);
            }
        });
        jtfCantidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfCantidadKeyTyped(evt);
            }
        });
        add(jtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 67, -1));

        jtfPrecioU.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPrecioU.setFocusable(false);
        jtfPrecioU.setPreferredSize(new java.awt.Dimension(70, 25));
        jtfPrecioU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfPrecioUActionPerformed(evt);
            }
        });
        add(jtfPrecioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 70, 67, -1));

        jtfSubtotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfSubtotal.setFocusable(false);
        jtfSubtotal.setPreferredSize(new java.awt.Dimension(70, 25));
        add(jtfSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 70, 67, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bote-de-basura.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 39, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrecioUActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfPrecioUActionPerformed
    {//GEN-HEADEREND:event_jtfPrecioUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioUActionPerformed

    public JButton getBtnEliminar()
    {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar)
    {
        this.btnEliminar = btnEliminar;
    }

    private void jtfCantidadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfCantidadActionPerformed
    {//GEN-HEADEREND:event_jtfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCantidadActionPerformed

    public JTextField getJtfCantidad()
    {
        return jtfCantidad;
    }

    public void setJtfCantidad(JTextField jtfCantidad)
    {
        this.jtfCantidad = jtfCantidad;
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed

        Container parent = getParent();
        if (parent != null)
        {
            int index = parent.getComponentZOrder(this);
            parent.remove(this); // Eliminar este panel del contenedor
            // Si hay un componente siguiente (el espacio), eliminarlo también
            if (index < parent.getComponentCount())
            {
                Component siguiente = parent.getComponent(index);
                if (siguiente instanceof Box.Filler)
                { // Verifica que sea el espacio creado con Box.createRigidArea
                    parent.remove(siguiente);
                }
            }
            parent.revalidate(); // Recalcular el layout
            parent.repaint();    // Redibujar el contenedor
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtfCantidadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfCantidadKeyPressed
    {//GEN-HEADEREND:event_jtfCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCantidadKeyPressed

    private void jtfCantidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfCantidadKeyTyped
    {//GEN-HEADEREND:event_jtfCantidadKeyTyped
        // TODO add your handling code here:
           
    }//GEN-LAST:event_jtfCantidadKeyTyped

    public JTextField getJtfSubtotal()
    {
        return jtfSubtotal;
    }

    public void setJtfSubtotal(JTextField jtfSubtotal)
    {
        this.jtfSubtotal = jtfSubtotal;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfPrecioU;
    private javax.swing.JTextField jtfSubtotal;
    private javax.swing.JLabel lblNombreProducto;
    // End of variables declaration//GEN-END:variables
}
