/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.Mensaje;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class VtnCorteCaja extends javax.swing.JFrame {

    /**
     * Creates new form CorteCaja
     */
    public VtnCorteCaja() {
        initComponents();
        jtfFecha.setText("22/02/2024");
        jtfTotalVentas.setText("1523.5");
       jtfEmpleado.setText("Emmanuel Martinez");
       jtfDiferencia.setText("0.0");
        agregarPanel();
        setIconImage(getIconImage());
    }
   
    private void agregarPanel() {
        // Crea una instancia del panel

        // Establece un layout para el JPanel donde se agregará el mapa
        jPanel1.setLayout(new BorderLayout());

        // Agrega el panel a vista empleado

        // Refresca el panel para que se vea el mapa
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfEmpleado = new javax.swing.JTextField();
        jtfTotalVentas = new javax.swing.JTextField();
        jtfFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfDiferencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfDineroEnCaja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurant Esencia y Sazón");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total De Ventas: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 41));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dinero En Caja :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 41));

        jtfEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        jtfEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtfEmpleado.setFocusable(false);
        jtfEmpleado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 310, 30));

        jtfTotalVentas.setBackground(new java.awt.Color(204, 204, 204));
        jtfTotalVentas.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtfTotalVentas.setFocusable(false);
        jtfTotalVentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfTotalVentasActionPerformed(evt);
            }
        });
        jPanel1.add(jtfTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 310, 30));

        jtfFecha.setBackground(new java.awt.Color(204, 204, 204));
        jtfFecha.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtfFecha.setFocusable(false);
        jtfFecha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jtfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 120, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diferencia:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 41));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha del Corte:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 41));

        jtfDiferencia.setBackground(new java.awt.Color(204, 204, 204));
        jtfDiferencia.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtfDiferencia.setFocusable(false);
        jtfDiferencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfDiferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jtfDiferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 310, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Empleado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 115, 41));

        jButton2.setBackground(new java.awt.Color(207, 181, 59));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REALIZAR CORTE");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 210, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CORTE DE CAJA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jtfDineroEnCaja.setBackground(new java.awt.Color(204, 204, 204));
        jtfDineroEnCaja.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtfDineroEnCaja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfDineroEnCajaActionPerformed(evt);
            }
        });
        jPanel1.add(jtfDineroEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 310, 30));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton rojo.png"))); // NOI18N
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton amarillo.png"))); // NOI18N
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton verde.png"))); // NOI18N
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmpleadoActionPerformed

    private void jtfTotalVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTotalVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalVentasActionPerformed

    private void jtfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaActionPerformed

    private void jtfDiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiferenciaActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu1MouseClicked
    {//GEN-HEADEREND:event_jMenu1MouseClicked
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu2MouseClicked
    {//GEN-HEADEREND:event_jMenu2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jtfDineroEnCajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfDineroEnCajaActionPerformed
    {//GEN-HEADEREND:event_jtfDineroEnCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDineroEnCajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new VtnMostrarEmpleadosSimplificada().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Mensaje.exito(this, "Corte Guardado");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCorteCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfDiferencia;
    private javax.swing.JTextField jtfDineroEnCaja;
    private javax.swing.JTextField jtfEmpleado;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfTotalVentas;
    // End of variables declaration//GEN-END:variables
}
