/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.Mensaje;
import dao.CorteDAO;
import dao.DetalleCorteDAO;
import dao.EmpleadoDAO;
import dao.VentaDAO;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modelo.CorteDeCaja;
import modelo.Empleado;
import modelo.Venta;

/**
 *
 * @author User
 */
public class VtnCorteCaja extends javax.swing.JFrame
{

    /**
     * Creates new form CorteCaja
     */
    private com.toedter.calendar.JDateChooser fechaCorte;

    public VtnCorteCaja()
    {
        initComponents();
        cargarEmpleadosEnComboBox();
        fechaCorte = new com.toedter.calendar.JDateChooser();

        fechaCorte.setBounds(0, 0, 150, 30);

        calendario.setLayout(null);

        calendario.add(fechaCorte);

        agregarPanel();
        setIconImage(getIconImage());
        configurarCalculoDiferencia();
    }

    private void agregarPanel()
    {
        jPanel1.setLayout(new BorderLayout());
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        empleados = new javax.swing.JComboBox<>();
        calendario = new javax.swing.JPanel();
        jtfDineroEnCaja = new javax.swing.JTextField();
        jtfTotalVentas = new javax.swing.JTextField();
        jtfDiferencia = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurant Esencia y Sazón");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total De Ventas: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 41));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dinero En Caja :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 41));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diferencia:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 41));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha del Corte:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 41));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Empleado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 115, 41));

        jButton2.setBackground(new java.awt.Color(207, 181, 59));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REALIZAR CORTE");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 210, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CORTE DE CAJA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jPanel1.add(empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 310, 30));
        jPanel1.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 150, 30));

        jtfDineroEnCaja.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jPanel1.add(jtfDineroEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 310, 30));

        jtfTotalVentas.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtfTotalVentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfTotalVentasActionPerformed(evt);
            }
        });
        jPanel1.add(jtfTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 310, 30));

        jtfDiferencia.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jPanel1.add(jtfDiferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 310, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 510));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton rojo.png"))); // NOI18N
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton amarillo.png"))); // NOI18N
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton verde.png"))); // NOI18N
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu1MouseClicked
    {//GEN-HEADEREND:event_jMenu1MouseClicked
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu2MouseClicked
    {//GEN-HEADEREND:event_jMenu2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        try
        {

            if (fechaCorte.getDate() == null)
            {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha para el corte de caja.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.sql.Date fechaSeleccionada = new java.sql.Date(fechaCorte.getDate().getTime());

            if (jtfTotalVentas.getText().isEmpty() || jtfDineroEnCaja.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double totalVentas;
            double dineroCaja;

            try
            {
                totalVentas = Double.parseDouble(jtfTotalVentas.getText());
                dineroCaja = Double.parseDouble(jtfDineroEnCaja.getText());
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String nombreEmpleado = (String) empleados.getSelectedItem();
            if (nombreEmpleado == null || nombreEmpleado.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            EmpleadoDAO empleadoDAO = new EmpleadoDAO();
            long idEmpleado = empleadoDAO.obtenerIdEmpleadoPorNombre(nombreEmpleado);

            VentaDAO ventaDAO = new VentaDAO();
            List<Long> ventasSinCorte = ventaDAO.obtenerVentasSinCorte();

            if (ventasSinCorte.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "No hay ventas sin corte de caja.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            CorteDeCaja nuevoCorte = new CorteDeCaja(idEmpleado, fechaSeleccionada, totalVentas, dineroCaja, ventasSinCorte);

            CorteDAO corteDAO = new CorteDAO();
            long idCorteDeCaja = corteDAO.agregarCorteDeCaja(nuevoCorte);

            if (idCorteDeCaja != -1)
            {

                DetalleCorteDAO detalleCorteDAO = new DetalleCorteDAO();
                boolean detallesExito = detalleCorteDAO.agregarDetalleCorte(idCorteDeCaja, ventasSinCorte);

                if (detallesExito)
                {
                    JOptionPane.showMessageDialog(this, "Corte de caja registrado con éxito, incluyendo los detalles.");
                } else
                {
                    JOptionPane.showMessageDialog(this, "Error al registrar los detalles del corte.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "Error al registrar el corte de caja.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void jtfTotalVentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfTotalVentasActionPerformed
    {//GEN-HEADEREND:event_jtfTotalVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalVentasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        VentaDAO ventasDAO = new VentaDAO();
        double totalVentas = ventasDAO.obtenerTotalVentas();

        jtfTotalVentas.setText(String.format("%.2f", totalVentas));

        calcularDiferencia();
    }//GEN-LAST:event_formWindowOpened

    private void calcularDiferencia()
    {
        try
        {
            String totalVentasTexto = jtfTotalVentas.getText().trim();
            String dineroCajaTexto = jtfDineroEnCaja.getText().trim();

            if (totalVentasTexto.isEmpty() || dineroCajaTexto.isEmpty())
            {
                jtfDiferencia.setText("");
                return;
            }

            double totalVentas = Double.parseDouble(totalVentasTexto);
            double dineroCaja = Double.parseDouble(dineroCajaTexto);

            double diferencia = totalVentas - dineroCaja;

            jtfDiferencia.setText(String.format("%.2f", diferencia));
        } catch (NumberFormatException e)
        {
            jtfDiferencia.setText("Error");
        }
    }

    private void configurarCalculoDiferencia()
    {
        jtfDineroEnCaja.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                calcularDiferencia();
            }

            @Override
            public void removeUpdate(DocumentEvent e)
            {
                calcularDiferencia();
            }

            @Override
            public void changedUpdate(DocumentEvent e)
            {
                calcularDiferencia();
            }
        });
    }

    private void cargarEmpleadosEnComboBox()
    {
        EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<String> nombresEmpleados = empleadoDAO.obtenerNombresEmpleados();

        empleados.removeAllItems();

        for (String nombre : nombresEmpleados)
        {
            empleados.addItem(nombre);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnCorteCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendario;
    private javax.swing.JComboBox<String> empleados;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfDiferencia;
    private javax.swing.JTextField jtfDineroEnCaja;
    private javax.swing.JTextField jtfTotalVentas;
    // End of variables declaration//GEN-END:variables
}
