/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.BtnEntero;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import dao.ProductoDAO;
import dao.VentaDAO;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import modelo.DetalleVenta;
import modelo.Producto;
import modelo.Venta;

/**
 *
 * @author User
 */
public class VtnCuentaAbierta extends javax.swing.JFrame
{

    /**
     * Creates new form CuentaAbierta
     */
    Venta venta = new Venta();

    public Venta getVenta()
    {
        return venta;
    }

    public void setVenta(Venta venta)
    {
        this.venta = venta;
    }

    public VtnCuentaAbierta()
    {

        initComponents();
        configurarVtnProductos();
        panelDetalles.setLayout(new BoxLayout(panelDetalles, BoxLayout.Y_AXIS));

        setIconImage(getIconImage());
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblIVA = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDetalles = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lblCerrar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurant Esencia y Sazón");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIVA.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblIVA.setForeground(new java.awt.Color(255, 255, 255));
        lblIVA.setText("IVA");
        jPanel1.add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 80, 30));

        btnPagar.setBackground(new java.awt.Color(207, 181, 59));
        btnPagar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 110, 40));

        btnVolver.setBackground(new java.awt.Color(207, 181, 59));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 120, 40));

        btnAgregar.setBackground(new java.awt.Color(207, 181, 59));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 110, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelDetalles.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalles.setLayout(new javax.swing.BoxLayout(panelDetalles, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelDetalles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 740, 370));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VENTA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblSub.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblSub.setForeground(new java.awt.Color(255, 255, 255));
        lblSub.setText("Sub");
        jPanel1.add(lblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 80, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 50, 30));

        jtfTotal.setBackground(new java.awt.Color(204, 204, 204));
        jtfTotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtfTotal.setEnabled(false);
        jtfTotal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jtfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 80, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subtotal:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 80, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IVA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 50, 30));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton rojo.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(lblCerrar);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton amarillo.png"))); // NOI18N
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton verde.png"))); // NOI18N
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        VentaDAO dao = new VentaDAO();
    ProductoDAO daoProducto = new ProductoDAO();

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:

        if (venta.isValida())
        {
            if (Mensajes.pregunta(this, "Desea Finalizar la venta?") == 0)
            {
                int id = dao.guardarVenta(venta);
                if (id != -1)
                {
                    dao.guardarDetallesVenta(id, venta.getDetallesVenta());
                    Mensajes.exito(this, "Venta guardada con éxito");
                    Venta nvaVenta = new Venta();
                    venta = nvaVenta;

                    repintarVistaDetalles();

                }
            }
        } else
        {
            Mensajes.error(this, "Debe agregar productos");
        }


    }//GEN-LAST:event_btnPagarActionPerformed

    private void actualizarStockProductosEnBD(List<DetalleVenta> detallesVenta)
    {
        for (DetalleVenta detalle : detallesVenta)
        {
            boolean actualizado = daoProducto.actualizarCantidadProducto(detalle.getProducto().getCodigo(), detalle.getCantidadProducto());
            if (!actualizado)
            {
                System.err.println("No se pudo actualizar el inventario del producto con código: " + detalle.getProducto().getCodigo());
            }
        }

    }

    public void cancelarVenta()
    {
        ProductoDAO dao = new ProductoDAO();
        if (venta!=null)
        {
            for (DetalleVenta d : venta.getDetallesVenta())
            {
                dao.insertarCantidadProducto(d.getProducto().getCodigo(), d.getCantidadProducto());

            }
            
        }
    }
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        cancelarVenta();
        dispose();
        new VtnVistaEmpleado().setVisible(true);

    }//GEN-LAST:event_btnVolverActionPerformed

    public JButton getBtnVolver()
    {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver)
    {
        this.btnVolver = btnVolver;
    }

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblCerrarMouseClicked
    {//GEN-HEADEREND:event_lblCerrarMouseClicked
      
        System.exit(0);
        
    }//GEN-LAST:event_lblCerrarMouseClicked

    public JMenu getLblCerrar()
    {
        return lblCerrar;
    }

    public void setLblCerrar(JMenu lblCerrar)
    {
        this.lblCerrar = lblCerrar;
    }

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu2MouseClicked
    {//GEN-HEADEREND:event_jMenu2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jMenu2MouseClicked
    VtnVerProductos vtnProductos = new VtnVerProductos();

    private void configurarVtnProductos()
    {
        programarBoton();

    }

    public void setCantidadDetalleVenta(String nombreProducto, int nvaCantidad)
    {
        DetalleVenta detalle = venta.buscarDetallePorNombre(nombreProducto);
        if (detalle != null)
        {
            detalle.setCantidadProducto(nvaCantidad);
        }
        System.out.println(detalle.getProducto().getNombre() + " " + detalle.getCantidadProducto());

    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed

        //agregarDetalleAvista("Cocacola", "25");
        vtnProductos.setVisible(true);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtfTotalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfTotalActionPerformed
    {//GEN-HEADEREND:event_jtfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalActionPerformed

    private void programarBoton()
    {
        JButton btnAgregar = vtnProductos.getBtnBotonProgramable();
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                agregarProductoAventa(1);

            }
        });
        //  vtnProductos.setBtnBotonProgramable(btnAgregar);
    }

    private void agregarProductoAventa(int cantidad)
    {
        Producto producto = vtnProductos.obtenerProductoSeleccionado();

        if (producto != null)
        {
            if (producto.getCantidadStock() == 0)
            {
                Mensajes.error(this, "la cantidad en inventario es insuficiente");
                return;

            }
            if (venta.buscarDetallePorNombre(producto.getNombre()) != null)
            {
                
                    DetalleVenta nvoDetalle = new DetalleVenta(producto, cantidad);
                    venta.agregarDetalle(nvoDetalle);
                    ProductoDAO dao = new ProductoDAO();
                    dao.actualizarCantidadProducto(producto.getCodigo(), cantidad);
                    repintarVistaDetalles();
                
            } else
            {
                if (producto.getCantidadStock() > 0)
                {
                    DetalleVenta nvoDetalle = new DetalleVenta(producto, 1);
                    ProductoDAO dao = new ProductoDAO();
                    dao.actualizarCantidadProducto(producto.getCodigo(), cantidad);
                    venta.agregarDetalle(nvoDetalle);
                    repintarVistaDetalles();
                }
            }

            System.out.println(venta.toString());

        } else
        {
            System.out.println("ninguno Seleccionado");
        }

    }

    public JButton getBtnAgregarDetalle()
    {
        return btnAgregar;
    }

    public void repintarVistaDetalles()
    {
        List<DetalleVenta> detalles = venta.getDetallesVenta();
        lblIVA.setText("");
        lblSub.setText("");
        jtfTotal.setText("");

        panelDetalles.removeAll();
        if (!detalles.isEmpty())
        {
            for (DetalleVenta d : detalles)
            {
                agregarDetalleAPanel(d);
            }

            lblIVA.setText(String.format("%.1f", venta.calcularImpuestos()));
            lblSub.setText(String.format("%.1f", venta.getSubTotal()));
            jtfTotal.setText(String.format("%.1f", venta.getTotal()));
            System.out.println("TOTAL: " + String.format("%.1f", venta.getTotal()));

        }
        panelDetalles.revalidate();
        panelDetalles.repaint();
    }
    PanelDetalle panelNvoDetalle;

    private void agregarDetalleAPanel(DetalleVenta detalle)
    {
        panelNvoDetalle = new PanelDetalle(detalle.getProducto().getNombre(), detalle.getProducto().getPrecioVenta() + "");
        panelNvoDetalle.getJtfSubtotal().setText(detalle.getSubTotal() + "");
        panelNvoDetalle.getJtfCantidad().setText(detalle.getCantidadProducto() + "");
        panelNvoDetalle.getBtnEliminar().addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                ProductoDAO dao = new ProductoDAO();
                venta.eliminarDetalle(detalle);
                dao.insertarCantidadProducto(detalle.getProducto().getCodigo(), detalle.getCantidadProducto());

                repintarVistaDetalles();

            }
        });

        panelDetalles.add(panelNvoDetalle);
        panelDetalles.add(Box.createRigidArea(new Dimension(0, 10))); // Espacio de 10px entre paneles
        panelDetalles.revalidate();
        panelDetalles.repaint();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnCuentaAbierta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnCuentaAbierta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnCuentaAbierta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnCuentaAbierta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnCuentaAbierta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JMenu lblCerrar;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblSub;
    private javax.swing.JPanel panelDetalles;
    // End of variables declaration//GEN-END:variables
}
