/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import componenteVenta.GestorBotones;
import controlador.controladorVenta;
import java.awt.Color;
import componenteVenta.GestorBotones.*;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import modelo.Venta;

/**
 *
 * @author User
 */
public class VtnMesas extends javax.swing.JFrame
{

    /**
     * Creates new form Centa
     */
    GestorBotones gestorBotones = new GestorBotones();

    public VtnMesas()
    {

        initComponents();
        setIconImage(getIconImage());
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    public VtnMesas(List<JButton> mesas, JButton agregarMesa, JButton jButtonEliminar, JLabel jLabel1, JLabel jLabel4, JLabel jLabel5, JLabel jLabel6, JPanel jPanel1, JScrollPane jScrollPane1, JPanel panelMesas) throws HeadlessException
    {
        this.agregarMesa = agregarMesa;
        this.jButtonEliminar = jButtonEliminar;
        this.jLabel1 = jLabel1;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jLabel6 = jLabel6;
        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.panelMesas = panelMesas;
    }
    List<JButton> mesas = new ArrayList<>();

    public void guardarMesas()
    {
        mesas.clear(); // Evita duplicados
        for (Component comp : panelMesas.getComponents())
        {
            if (comp instanceof JButton)
            {
                mesas.add((JButton) comp);
            }
        }

        try
        {
            gestorBotones.guardarBotones(mesas, "mesas.dat");
            System.out.println("Mesas guardadas correctamente.");
        } catch (IOException e)
        {
            JOptionPane.showMessageDialog(null, "No se pudieron guardar las mesas");
            e.printStackTrace();
        }
    }

    public void cargarMesas()
    {
        try
        {
            List<JButton> botonesCargados = gestorBotones.cargarBotones("mesas.dat", panelMesas, (ActionEvent e) ->
            {
                // Si es necesario manejar otros eventos al hacer clic
                
            });

            for (JButton boton : botonesCargados)
            {
                // Agregar MouseListener para manejar clics
                boton.addMouseListener(new java.awt.event.MouseAdapter()
                {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        manejarClickBotonMesa(evt, boton);
                    }
                });

                // Agregar el botón al panel
                panelMesas.add(boton);
            }

            panelMesas.revalidate();
            panelMesas.repaint();
            System.out.println("Mesas cargadas correctamente.");
        } catch (IOException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las mesas");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        agregarMesa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMesas = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mesas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 70, 30));

        agregarMesa.setBackground(new java.awt.Color(207, 181, 59));
        agregarMesa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        agregarMesa.setForeground(new java.awt.Color(255, 255, 255));
        agregarMesa.setText("Agregar Mesa");
        agregarMesa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarMesaActionPerformed(evt);
            }
        });
        jPanel1.add(agregarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton rojo.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton amarillo.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton verde.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelMesas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMesasLayout = new javax.swing.GroupLayout(panelMesas);
        panelMesas.setLayout(panelMesasLayout);
        panelMesasLayout.setHorizontalGroup(
            panelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        panelMesasLayout.setVerticalGroup(
            panelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelMesas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 490, 410));

        jButtonEliminar.setBackground(new java.awt.Color(207, 181, 59));
        jButtonEliminar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar Mesa");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private JButton mesaSeleccionada = null;
    private final Color colorOriginal = UIManager.getColor("Button.background");
    private void agregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMesaActionPerformed

        // Pedir el nombre de la mesa
        String nombre = JOptionPane.showInputDialog("Nombre de la mesa");
        if (nombre == null || nombre.trim().isEmpty())
        {
            return; // Salir si no se introduce un nombre
        }

        // Crear una nueva venta asociada al botón
        Venta nuevaVenta = new Venta();

        // Crear un nuevo botón para la mesa
        JButton nvaMesa = new JButton(nombre);
        nvaMesa.setBounds(0, 0, anchoBoton, altoBoton); // Tamaño por defecto
        nvaMesa.putClientProperty("venta", nuevaVenta); // Asociar la venta al botón

        // Cambiar color al seleccionar
        nvaMesa.addMouseListener(new java.awt.event.MouseAdapter()
        {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                manejarClickBotonMesa(evt, nvaMesa);
            }
        });

        // Agregar el botón al panel
        panelMesas.add(nvaMesa);
        reajustarBotones(); // Actualizar posiciones

        // Guardar el estado de las mesas en el archivo
        guardarMesas();


    }//GEN-LAST:event_agregarMesaActionPerformed
    private void manejarClickBotonMesa(java.awt.event.MouseEvent evt, JButton boton)
    {
        if (evt.getClickCount() == 2)
        { // Detectar doble clic
            Venta venta = (Venta) boton.getClientProperty("venta");
            if (venta != null)
            {
                System.out.println("Venta asociada: " + venta);
               
                System.out.println("Total: " + venta.getTotal());
            } else
            {
                System.out.println("No hay una venta asociada.");
            }
        } else if (evt.getClickCount() == 1)
        { // Detectar clic simple
            if (mesaSeleccionada != null)
            {
                mesaSeleccionada.setBackground(colorOriginal);
            }

            mesaSeleccionada = boton;
            boton.setBackground(Color.pink);
        }
    }

// Método para reajustar la posición de los mesas después de la eliminación
    int anchoBoton = 230;
    int altoBoton = 130;
    int espacioHorizontal = 20;
    int espacioVertical = 20;

    private void reajustarBotones()
    {
        // Volver a agregar solo los mesas restantes
        int botonesExistentes = panelMesas.getComponentCount();

        // Ajustar la posición de cada botón
        for (int i = 0; i < botonesExistentes; i++)
        {
            JButton boton = (JButton) panelMesas.getComponent(i);

            // Calcular la posición para cada botón (2 columnas)
            int columna = i % 2;  // 0 = primera columna, 1 = segunda columna
            int fila = i / 2;     // Incrementa fila cada 2 mesas

            int x = columna * (anchoBoton + espacioHorizontal);  // Posición X
            int y = fila * (altoBoton + espacioVertical);        // Posición Y

            // Establecer la nueva posición y tamaño del botón
            boton.setBounds(x, y, anchoBoton, altoBoton);
        }

        // Ajustar el tamaño preferido del panel según el número de filas y columnas
        int columnas = 2; // Número fijo de columnas
        int filas = (int) Math.ceil(botonesExistentes / (double) columnas);

        int panelWidth = columnas * (anchoBoton + espacioHorizontal) - espacioHorizontal;
        int panelHeight = filas * (altoBoton + espacioVertical) - espacioVertical;

        // Establecer el tamaño preferido del panel
        panelMesas.setPreferredSize(new Dimension(panelWidth, panelHeight));

        // Revalidar el panel y el JScrollPane
        panelMesas.revalidate();
        panelMesas.repaint();
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel1MouseClicked
    {//GEN-HEADEREND:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel4MouseClicked
    {//GEN-HEADEREND:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarActionPerformed
    {//GEN-HEADEREND:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:

        if (mesaSeleccionada != null)
        {
            if (JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar la mesa")
                    == 0)
            {

                // Eliminar el botón seleccionado del panel
                panelMesas.remove(mesaSeleccionada);
                Venta venta = (Venta) mesaSeleccionada.getClientProperty("venta");
                if (venta != null)
                {
                    if (controladorVenta.gestorVentaMesas.getVentas() != null)
                    {
                        controladorVenta.gestorVentaMesas.getVentas().remove(venta);
                    }
                }
                // Limpiar la selección
                mesaSeleccionada = null;

                // Reajustar la posición de los mesas restantes
                reajustarBotones();
                guardarMesas();

                // Actualizar el diseño
                panelMesas.revalidate();
                panelMesas.repaint();
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "No hay ningúna mesa seleccionada.");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        cargarMesas();

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnMesas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnMesas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnMesas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnMesas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarMesa;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMesas;
    // End of variables declaration//GEN-END:variables
}
